version: '3'
services:
  backend-service:
    image: jackblaster/container_ml_ops_td3:latest
    ports:
      - "8080:5000"
    environment:
      - CURRENT_ENVIRONMENT=backend_env
    volumes:
      - backend-data:/app/back/data

  frontend-service:
    image: jackblaster/frontend_image_td3:latest
    ports:
      - "8081:80"
    environment:
      - WS_BACK_URL=http://backend-service:8080

volumes:
  backend-data: